### PR TITLE
Created a Graphing Notebook for Deliverable 2

### PR DESCRIPTION
**Pull request by varocarras**
I started a graphing Jupyter notebook, added some helper functions to organize the data and retrieve it, also created some basic visualizations for Temperature and Wind speed.

Also added .gitignore that works with all folders including Deliverable 2.

This resolves in a general way issue #10, although more extensive visualizations are encouraged.

### CODE REVIEW

**Comment by varocarras** [comment]
This conflicting .DS_Store errors will no longer occur when we commit this version of .gitignore

**Comment by varocarras** [comment]
I also thought it makes more sense to just work on master and then merge into Deliverable 2 when we want to turn it in. 

If you don't think so, just change the base to Deliverable 2 instead.

**Comment by icyair100** [comment]
Can you change the base branch to deliverable 2 instead of master

**Review by icyair100 — CHANGES_REQUESTED** [review]
Could you merge into the deliverable2 branch

**Comment by varocarras** [comment]
> Could you merge into the deliverable2 branch

Done!

**Review by icyair100 — APPROVED** [review]

**Pull request merged**
